config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :restaurants do
    resources :reviews, only: [:create, :new, :destroy]
  end
    # resources :reviews, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy # can call any restaurant instance e.g. @restaurant.reviews
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true
  validates :category, presence: true, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"]}
  # category must belong to ["chinese", "italian", "japanese", "french", "belgian"]
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
  validates :content, presence: true, length: { minimum: 10 }
  validates :rating, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

  # Get/ restaurants
  def index
    @restaurants = Restaurant.all
  end
  # Get /restaurants/1
  def show
    @restaurant = Restaurant.find(params[:id])
  end
  # GET /restaurants/new

  def new
    @restaurant = Restaurant.new
  end

  def edit
  end


  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was succesfully created.'
    else
      render :new
    end
  end

  def update
    if @restaurant.update(restaurant_params)
      redirect_to @restaurant, notice: 'Restaurant was successfully updated'
    else
      render :edit
    end
  end


  # DELETE / restaurants/1

  def destroy
    @restaurant = Restaurant.find(params[:id])
    @restaurant.destroy
    redirect_to restaurants_path
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :phone_number, :category)
  end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :find_restaurant, only: [:new, :create]
  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.restaurant = @restaurant
    if @review.save
      redirect_to restaurant_path(@restaurant)
    else
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @review.destroy
    redirect_to restaurant_path(@review.restaurant)
  end

  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants</h1>

<% @restaurants.each do |restaurant| %>
<div class="card">
  <h2><%= link_to restaurant.name, restaurant_path(restaurant) %></h2>
    <ul>
      <li><%= restaurant.address %></li>
      <li><%= restaurant.phone_number %></li>
      <li><%= restaurant.category %></li>
    </ul>
  </div>
<% end %>

app/views/restaurants/new.html.erb
<h1>New Restaurant</h1>
<div class="card"><%= form_for(@restaurant) do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :address %>
  <%= f.text_field :address %>
  <%= f.label :phone_number %>
  <%= f.text_field :phone_number %>
  <%= f.label :category %>
  <%= f.text_field :category %>
  <%= f.submit %>
  </div>

<% end %>

app/views/restaurants/show.html.erb
<div class="card">
  <h2><%= @restaurant.name %></h2>
    <ul>
      <li><%= @restaurant.address %></li>
      <li><%= @restaurant.phone_number %></li>
      <li><%= @restaurant.category %></li>
    </ul>

    <% @restaurant.reviews.each do |review| %>
    <p><%= review.content %></p>
    <p><%= review.rating %></p>
    <p><%= link_to "Delete", restaurant_review_path(@restaurant, review), method: :delete %></p>
    <hr>
    <% end %>

    <%= link_to "Return", restaurants_path %>
    <%= link_to "Delete", restaurant_path(@restaurant), method: :delete, data: { confirm: "Are you sure?"} %>
    <%= link_to "Ad a new review, jerkface!", new_restaurant_review_path(@restaurant) %>
  </div>

app/views/reviews/new.html.erb
<%= simple_form_for([@restaurant, @review ]) do |f| %>
  <%= f.input :content %>
  <%= f.input :rating %>
  <%= f.submit class: 'btn btn-primary' %>
<% end %>